- name: greetd | Ensure /etc/greetd directory exists
  become: true
  ansible.builtin.file:
    path: /etc/greetd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: greetd | Template greetd config
  become: true
  ansible.builtin.template:
    src: greetd/config.toml
    dest: /etc/greetd/config.toml
    owner: root
    group: root
    mode: "0644"

- name: greetd | Enable greetd service
  become: true
  ansible.builtin.systemd_service:
    name: greetd.service
    state: started
    enabled: true
