- name: Include tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - intel-undervolt.yml
    - cpu-frequency.yml
    - ssd.yml
    - power-management.yml
    - thunderbolt.yml
    - system.yml
    - fstab.yml
    - backlight.yml
    - keyboard.yml
    - rsync.yml
    - greetd.yml
    - grub.yml
