- name: power-management | Disable Bluetooth
  become: true
  ansible.builtin.command: rfkill block bluetooth
  changed_when: true

- name: system | Regenerate the initramfs
  become: true
  ansible.builtin.command: mkinitcpio -P
  changed_when: true

- name: system | Set Firefox as default web browser
  ansible.builtin.command: xdg-settings set default-web-browser firefox.desktop
  changed_when: true

- name: system | Set gsettings color-scheme to prefer-dark
  ansible.builtin.command: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  changed_when: true

- name: grub | mkconfig
  become: true
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  changed_when: true
